
services:
      java-app:
        
        image: java-app:v1
        container_name: "expensesapp"
        networks:
           expenses-app-nw:
        environment:
          SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"


          SPRING_DATASOURCE_USERNAME: "root"
          SPRING_DATASOURCE_PASSWORD: "Test@123"
          
        depends_on: 
          mysql_db:
            condition: service_healthy
        restart: always
        ports:
          - "8080:8080"
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
          interval: 15s
          timeout: 5s
          retries: 3
      


      mysql_db:
        image: mysql:latest
        container_name: "mysql"
        networks: 
           expenses-app-nw:
        environment: 
          MYSQL_ROOT_PASSWORD: "Test@123"
          MYSQL_DATABASE: "expenses_tracker"
        restart: always
        ports:
          - "3306:3306"
        healthcheck:
          test: [ "CMD", "mysqladmin" , "ping", "-h", "localhost", "-uroot" , "-pTest@123" ]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 60s
        volumes:
          -  mysql-data:/var/lib/mysql

networks:
   expenses-app-nw:


volumes:
  mysql-data:
